### ISSUE TITLE
500 Server Error

### ISSUE THREAD

**Issue by rpmesta395** [zimbra-api/zimbra-api#50]
I am trying to create new account, 
**My code is like** 
use Zimbra\Enum\AccountBy;
use Zimbra\Enum\AddressType;
use Zimbra\Enum\AlarmAction;
use Zimbra\Enum\FreeBusyStatus;
use Zimbra\Enum\InviteStatus;
use Zimbra\Enum\InviteClass;
use Zimbra\Enum\ParticipationStatus;
use Zimbra\Enum\Transparency;
use Zimbra\Struct\KeyValuePair;
use Zimbra\Admin\AdminFactory;
use Zimbra\Struct\AccountSelector;
use Zimbra\Admin\Request\CreateAccount;

$username = 'rag_testuser1234';
$domain = 'xxxxx.com';
$pass = 'Saanika@123';
$firstName='Ragtest';
$lastName='Mesta';
$adminApi = AdminFactory::instance('https://xxxxxxxxxxx:7071/service/admin/soap/');
$adminApi->auth('admin_usr_name','Admin_password');
$attrGivenName = new KeyValuePair ('givenName', $firstName);
$attrDisplayName = new KeyValuePair ('givenName', $firstName.' '.$lastName);

$create_account_res = $adminApi->createAccount($username.'@'.$domain, $pass,[$attrGivenName,$attrDisplayName]);

but get issue like 
Fatal error: Uncaught GuzzleHttp\Exception\ServerException: Server error: `POST https://192.168.5.30:7071/service/admin/soap/` resulted in a `500 Server Error` response: <soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope"><soap:Header><context xmlns="urn:zimbra"><change tok (truncated...) in /var/www/html/21charles/Zimbra/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113 Stack trace: #0 /var/www/html/21charles/Zimbra/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response)) #1 /var/www/html/21charles/Zimbra/vendor/guzzlehttp/promises/src/Promise.php(204): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response)) #2 /var/www/html/21charles/Zimbra/vendor/guzzlehttp/promises/src/Promise.php(153): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), NULL) #3 /var/www/html/21charles/Zimbra/vendor/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttp\P in /var/www/html/21charles/Zimbra/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113

could you help me

**Comment by iomarmochtar** [comment]
you may search to mailbox log `/opt/zimbra/log/mailbox.log` for the detail information.
